---
title: "2019 NCAA Men's Basketball"
output:
  html_document:
    df_print: paged
---

This is a quick writeup of my modeling of the NCAA men's basketball tournament

The main goal of this project was to produce a good enough model, that was simple. I had limited time to build this so didn't want to spend a bunch of time finiking with something complex.

Overall my bracket ends up matching the seeds with a couple exceptions.

Virginia for the win.

### Web Scraper

All games from the 2018-2019 season were scraped from the official NCAA website. Only the final score was of interest, this model could be extended to include each individual player's stats.

## Model Specification

My strategy was to assign a latent offensive $\lambda$ and defensive $\delta$ parameter for each team that feed into a poisson random variable to determine the score each team will score in a game. 

$$
Score_1 \sim Pois(e^{\lambda_1 - \delta_2}) \\
Score_2 \sim Pois(e^{\lambda_2 - \delta_1}) 
$$

As you can see a team's defensive parameter has an attenuating effect on the other teams score.

A hierarchical modeling approach was used, with each offensive and defensive parameter coming from a population distribution.

$$
\lambda_i \sim HalfNormal(0,\sigma_{\lambda}) \\
\delta_i \sim HalfNormal(0,\sigma_{\delta}) \\
\sigma_{\lambda} \sim Unif(0,\infty) \\
\sigma_{\delta} \sim Unif(0,\infty)
$$

The model was fit using [Stan](https://mc-stan.org/). Full model code below:

```{Stan, eval=F}
data{
    int T; //number teams
    int N; //number of games
    int tid1[N]; //team id of team 1 of game n
    int tid2[N]; //team id of team 2 of game n
    int pt1[N]; // pt for team 1
    int pt2[N]; // pt for team 2
}
parameters{
    real<lower=0> ofsd;
    real<lower=0> dfsd;
    vector<lower=0>[T] of;
    vector<lower=0>[T] df;
}
model{
    of ~ normal(0, ofsd);
    df ~ normal(0, dfsd);
    
    for(n in 1:N){
        pt1[n] ~ poisson_log(of[tid1[n]] - df[tid2[n]]);
        pt2[n] ~ poisson_log(of[tid2[n]] - df[tid1[n]]);
    }
}
```

## Monte Carlo Predictions

Predictions are made by taking the posterior of the parameters and simulating thousands of games. This allows win probabilities as well as score distributions to be infered.

## Followup

TBD

Enjoy.